import logo from '../assets/images/logo.png';
import banner from '../assets/images/banner.jpg';
import pet_trading from '../assets/images/pet_trading.jpg';
import heart_3D from '../assets/images/heart_3D.png';
import favorite_3D from '../assets/images/favorite_3D.png';
import setting_3D from '../assets/images/setting_3D.png';
import QA_3D from '../assets/images/QA_3D.png';
import community_3D from '../assets/images/community_3D.png';
import coin_3D from '../assets/images/coin_3D.png';
import cat_3D from '../assets/images/cat_3D.png';
import location from '../assets/images/location.png';
import order from '../assets/images/order.png';
import shopping from '../assets/images/shopping.png';
import wallet from '../assets/images/wallet.png';
import cancel from '../assets/images/cancel.png';
import noData from '../assets/images/noData.png';
import check from '../assets/images/check.png';
import cathouse from '../assets/images/cathouse.jpg';
import whiteCheck from '../assets/images/white_check.png';
import banking from '../assets/images/banking.png';
import cod from '../assets/images/cod.png';
import map_line from '../assets/images/map_line.png';
import edit from '../assets/images/edit.png';
import note from '../assets/images/note.png';
import angle_circle_right from '../assets/images/angle_circle_right.png';
import help_center from '../assets/images/help.png';
import logout from '../assets/images/logout.png';

export default { cat_3D, coin_3D, logo, banner, pet_trading, heart_3D, favorite_3D, setting_3D, QA_3D, community_3D, location, order, shopping, wallet, cancel, check, noData, cathouse, whiteCheck, banking, cod, map_line, edit,note,angle_circle_right,help_center, logout }