export const petData = [
  {
    id: "1",
    url: "https://img.freepik.com/free-photo/cute-smiley-dog-wearing-sunglasses_23-2148865714.jpg?w=826&t=st=1697865681~exp=1697866281~hmac=7b0c50c9a349786bff762d4baffc650e2601e99a506359fe861240c93132d301",
    type: "Chó",
    list: [
      {
        id: "1",
        type: "Retriever vàng",
        url: "https://img.freepik.com/free-psd/portrait-cute-golden-retriever-puppy-wearing-santa-hat_53876-73990.jpg?w=740&t=st=1697866398~exp=1697866998~hmac=a692f3b18da8b2df58e26d2fce45420233d57ae457a708e0677effd835523aa5",
        description: `Chó Retriever vàng là một giống chó lớn, đẹp, và thân thiện, chúng có nguồn gốc từ Vương quốc Anh. Chó Retriever vàng thường có bộ lông mềm mại màu vàng đậm hoặc màu vàng nhạt. Chúng rất thân thiện với con người, dễ dạy và thích tham gia vào mọi hoạt động của gia đình. Chó Retriever vàng thích chơi đùa và thích làm việc theo hướng dẫn, là lựa chọn lý tưởng cho các gia đình hoặc những người đang muốn nuôi một chú chó bạn đồng hành trung thành.`,
        origin: "Vương quốc Anh",
        life_span: 12,
        weight: "25 đến 32 Kg",
      },
      {
        id: "2",
        type: "Bulldog",
        url: "https://img.freepik.com/free-photo/looking-food-cute-black-french-bulldog-posing-isolated-white-studio-background_155003-46328.jpg?w=740&t=st=1697984015~exp=1697984615~hmac=74d1c45e7be0a6cd76643e107685606f3110bf9748dcf44fa4c9d8072870ecbb",
        description: `Chó Bulldog là một giống chó nhỏ đáng yêu và đặc biệt, chúng có nguồn gốc từ Anh. Chó Bulldog có đầu to, xương quai hàm rõ ràng, và có thể có một số nếp nhăn trên mặt. Chúng có bộ lông ngắn và mượt mà với màu sắc đa dạng như đen, trắng hoặc đốm. Mặc dù trông có vẻ hung dữ, nhưng chúng thật sự rất hiền lành, dễ bảo và thân thiện với con người. Chó Bulldog thích nằm yên ổn trong nhà và thích được vuốt ve.`,
        origin: "Anh",
        life_span: 8,
        weight: "18 đến 25 Kg",
      },
      {
        id: "3",
        type: "Poodle",
        url: "https://img.freepik.com/free-psd/view-adorable-pet-dog_23-2150161652.jpg?w=740&t=st=1697985803~exp=1697986403~hmac=690632e4f8243c62383b05120831627ab72f20556a78557b8b3d9082e2284f1c",
        description: `Chó Poodle là một giống chó thông minh, nổi tiếng với bộ lông sừng sững và phong cách độc đáo. Chúng có nguồn gốc từ Đức và được chia thành nhiều kích cỡ như tiêu chuẩn, miniature và toy. Chó Poodle thân thiện, dễ dạy và có tinh thần nghệ sĩ. Chúng thích thu hút sự chú ý và rất thích tham gia vào các hoạt động như đi bộ, chơi và huấn luyện.`,
        origin: "Đức",
        life_span: 15,
        weight: "2 đến 8 Kg",
      },
      {
        id: "4",
        type: "German Shepherd",
        url: "https://img.freepik.com/free-photo/cute-belgian-shepherd-sitting-grass_181624-30457.jpg?w=1380&t=st=1697866512~exp=1697867112~hmac=1df2e2011994e20b4e0db2e32ddff2900c44689822ae4f269717bb0255318bfd",
        description: `Chó German Shepherd là một giống chó thông minh, trung thành và đa năng, chúng có nguồn gốc từ Đức. Chó German Shepherd thường có bộ lông dày, màu đen và nâu, với tác dụng bảo vệ rất tốt. Chúng rất dễ dạy và thích làm việc, thích học hỏi và thích tham gia vào các hoạt động như chơi, di chuyển và huấn luyện. Chó German Shepherd là lựa chọn lý tưởng cho công việc bảo vệ, cứu hộ và hỗ trợ cảnh sát.`,
        origin: "Đức",
        life_span: 13,
        weight: "22 đến 40 Kg",
      },
      {
        id: "5",
        type: "Bulldog Pháp",
        url: "https://img.freepik.com/free-photo/french-bulldog-sitting-green-grass-outdoors_7502-8296.jpg?w=1060&t=st=1697985889~exp=1697986489~hmac=954b6be4fa886f167ced94049a9ca97dca3e12fea5c98c081260a40e42300637",
        description: `Chó Bulldog Pháp là một giống chó nhỏ đáng yêu, có nguồn gốc từ Pháp. Chúng có đầu lớn, cơ thể cấu trúc vững chắc và đôi tai lớn đặc trưng. Chó Bulldog Pháp thường có bộ lông ngắn, mịn màng và màu sắc đa dạng. Chúng thân thiện, nhút nhát và dễ dàng thích nghi với cuộc sống thành phố. Chó Bulldog Pháp thích nằm yên ổn trong nhà và thích tham gia vào các hoạt động nhẹ nhàng như đi dạo và chơi đùa.`,
        origin: "Pháp",
        life_span: 11,
        weight: "8 đến 14 Kg",
      },
      {
        id: "6",
        type: "Chó Siberian Husky",
        url: "https://img.freepik.com/free-photo/siberian-husky-dog-winter-forest_144627-10929.jpg?size=626&ext=jpg",
        description: `Chó Siberian Husky là một giống chó lao động trung bình, đẹp, ban đầu xuất xứ từ Đông Bắc Siberia. Nổi tiếng với bộ lông dày kép, đôi tai tam giác đứng, và các đốm đặc trưng, chúng năng động và thể thao. Chó Siberian Husky thân thiện, dịu dàng và tỉnh táo, là bạn đồng hành tốt cho các gia đình hoạt bát. Chúng nổi tiếng với sức chịu đựng và sẵn lòng làm việc.`,
        origin: "Siberia",
        life_span: 12,
        weight: "16 đến 27 Kg",
      },

      {
        id: "7",
        type: "Chó Labrador Retriever",
        url: "https://img.freepik.com/free-photo/little-labrador-retriever-playing-white-studio-background_155003-46342.jpg?w=740&t=st=1697866454~exp=1697867054~hmac=b5317e9da5ec3b8e115876db4d630a4fba3da8339ea2d595a9d4af76712ed458",
        description: `Chó Labrador Retriever là một giống chó trung bình đến lớn phổ biến xuất xứ từ Newfoundland, Canada. Chó Labrador nổi tiếng với tính cách thân thiện và hoạt bát, làm cho chúng trở thành thú cưng gia đình tuyệt vời và chó dẫn đường tốt. Chúng có bộ lông ngắn, dày đặc có màu sắc như vàng, đen và sô cô la. Chó Labrador thông minh, vâng lời và thích chơi và bơi.`,
        origin: "Canada",
        life_span: 12,
        weight: "25 đến 36 Kg",
      },
      {
        id: "8",
        type: "Chó Pomeranian",
        url: "https://img.freepik.com/free-photo/pet-dog-breed-animal-portrait-puppy-mammal_53876-30297.jpg?w=996&t=st=1697996119~exp=1697996719~hmac=7a9fc10bd54d5ec98eed55fac832b5a8851a4d0000b7af397a1a9c556f444dea",
        description: `Chó Pomeranian là một giống chó nhỏ cực kỳ đáng yêu, nổi tiếng với bộ lông dày và bồng bềnh. Ban đầu xuất xứ từ Đức và Ba Lan, chúng có bộ lông dày và lông rậm màu sắc đa dạng. Chó Pomeranian thông minh, hoạt bát và thân thiện, làm cho chúng trở thành bạn đồng hành lý tưởng cho người sống độc thân hoặc gia đình.`,
        origin: "Đức, Ba Lan",
        life_span: 12,
        weight: "1.4 đến 3.2 Kg",
      },

      {
        id: "9",
        type: "Chó Shih Tzu",
        url: "https://img.freepik.com/premium-photo/shih-tzu-sitting-panting-isolated-white_191971-16704.jpg?w=740",
        description: `Chó Shih Tzu là một giống chó nhỏ và đáng yêu xuất phát từ Trung Quốc. Chúng có bộ lông dày, phong cách và mặt ngắn đặc trưng. Chó Shih Tzu thân thiện, tình cảm và thích ở bên cạnh con người. Chúng thích được vuốt ve và chơi đùa, là lựa chọn tốt cho người sống ở căn hộ hoặc nhà nhỏ.`,
        origin: "Trung Quốc",
        life_span: 13,
        weight: "4.5 đến 7.3 Kg",
      },

      {
        id: "10",
        type: "Chó Beagle",
        url: "https://img.freepik.com/free-photo/beagle-tricolor-puppy-is-posing_155003-31772.jpg?w=1060&t=st=1697996189~exp=1697996789~hmac=ca59c9f10d2e40f3bff1c6c58545dd90410bd8f43603ef768af482d94a1cc9de",
        description:
          "Chó Beagle là một giống chó nhỏ đáng yêu và tròn trịa xuất phát từ Anh. Chúng có bộ lông ngắn mịn màng và màu sắc đa dạng như đen, trắng và nâu. Chó Beagle thông minh, năng động và thân thiện với con người, là lựa chọn tốt cho các gia đình có trẻ nhỏ. Chúng thích chạy nhảy và làm việc nhóm.",
        origin: "Anh",
        life_span: 12,
        weight: "9.1 đến 16 Kg",
      },

      {
        id: "11",
        type: "Chó Chihuahua",
        url: "https://img.freepik.com/free-photo/view-adorable-chihuahua-dog-house_23-2149880104.jpg?w=360&t=st=1697996207~exp=1697996807~hmac=9c02a71fc0c05ad30310a88fb44407b9b0ce733a5ac87e353a7c498ac1e04365",
        description:
          "Chó Chihuahua là một giống chó nhỏ với bộ lông ngắn hoặc dài, xuất phát từ Mexico. Chúng có kích thước nhỏ, trí thông minh và tính cách can đảm. Chó Chihuahua thường rất gắn bó với chủ nhân của mình và thích ở bên cạnh con người. Chúng thích được yêu chiều và cưng nựng.",
        origin: "Mexico",
        life_span: 12,
        weight: "0.9 đến 2.7 Kg",
      },
    ],
  },
  {
    id: "2",
    url: "https://static.wixstatic.com/media/9d8ed5_b8fcc13f08fc4374bb1f979e032b0eb7~mv2.jpg/v1/fit/w_600,h_567,al_c,q_20,enc_auto/file.jpg",
    type: "Mèo",
    list: [
      {
        id: "1",
        type: "Abyssinian",
        url: "https://dogily.vn/wp-content/uploads/2021/07/gia-meo-long-ngan-abyssinian.jpg",
        description: `Mèo Abyssinian có nguồn gốc từ châu Á, chúng có kích thước trung bình và thường nặng từ 3 đến 6kg. Mèo Abyssinian có bộ lông ngắn và màu sắc của bộ lông trải dài từ màu quế đến nâu vàng hay xanh lam. Để Abyssinian có bộ lông đẹp thì bạn nên sử dụng khăn len da cừu để đánh bóng. Abyssinian còn được gọi là "thỏ mèo", vì chúng có đôi tai nhỏ và nhọn. Giống mèo này rất hiếu động và thích chơi đùa với chủ và đặc biệt chúng rất ghét ở một mình. Vì thế nếu muốn rước một bé mèo Abyssinian về nhà thì bạn nên đảm bảo cho các bé có một sân chơi rộng rãi và được rào chắn cẩn thận nhé.`,
        origin: "Ai Cập",
        life_span: 12,
        weight: "Dưới 4.5 Kg",
      },
      {
        id: "2",
        type: "Tai xoắn",
        url: "https://sieupet.com/sites/default/files/meo_my_tai_xoan2.jpg",
        description: `Mèo tai xoắn là một giống mèo đột biến tự nhiên có nguồn gốc từ Mỹ. Giống mèo này sở hữu bộ lông ngắn hoặc trung bình, và điểm nổi bật là đôi tai cong (có thể gấp ra sau đến 180 độ). Giống mèo tai xoắn này rất hiếm, đặc biệt là bên ngoài nước Mỹ. Các chú mèo Mỹ tai xoắn thường rất dễ chịu và thích vui đùa, bên cạnh đó chúng cũng sẽ rất nhẹ nhàng với trẻ em và những chú mèo khác.`,
        origin: "Mỹ",
        life_span: 12,
        weight: "Dưới 4.5 Kg",
      },
      {
        id: "3",
        type: "Mỹ lông ngắn",
        url: "https://zoipet.com/wp-content/uploads/2022/10/meo-my-long-ngan-2-Copy.jpg",
        description: `Mèo Mỹ lông ngắn là một giống mèo có kích thước trung bình, chúng có một cái đầu tương đối rộng, tròn cùng một đôi tai khá ngắn nên khiến chúng có cảm giác mập mạp. Chúng rất mến chủ, tình cảm và thích gần gũi con người. Ngoài ra chúng cũng rất thân thiện và thích được chơi đùa. Bên cạnh đó bạn có biết giống mèo này rất hiếm ở châu u và là một “ngôi sao” nổi tiếng tại Mỹ và Nhật Bản không!`,
        origin: "Anh",
        life_span: 12,
        weight: "2 đến 10 Kg",
      },
      {
        id: "4",
        type: "Mèo nhà",
        url: "https://traicho.com/wp-content/uploads/2023/05/1-4-533x400.png",
        description: `Loài này là sự pha trộn của một số giống mèo. Đây là một thuật ngữ chung để gọi một loài động vật không rõ nguồn gốc, chúng còn được gọi là "mèo nhà". Chúng thường bị nhầm lẫn với giống mèo châu Âu vì mèo trong hẻm thường được tìm thấy nhiều nhất ở châu Âu. Bộ lông của chúng không có màu sắc đặc biệt và cơ thể của chúng không có tiêu chuẩn xác định. Tuy nhiên, chúng ta có thể nói rằng nhờ nguồn gốc đa dạng, chúng trở thành một loài động vật mạnh mẽ và là một thợ săn giỏi. Trong tiếng Pháp, tên của nó có nghĩa đen là "con mèo" bởi vì nó sống trên các mái nhà và trong các rãnh nước của Paris.`,
        origin: "Châu Âu",
        life_span: 12,
        weight: "Dưới 4.5 Kg",
      },
      {
        id: "5",
        type: "Siamese",
        url: "https://img.freepik.com/free-psd/beautiful-cat-portrait-isolated_23-2150186055.jpg?w=740&t=st=1697866638~exp=1697867238~hmac=cbfec352df6f4dfaeaa249b608c22b56c1ce7c00a43080d44fe9d9b52ec1dc75",
        description: `Mèo Siamese là một giống mèo có nguồn gốc từ Thái Lan. Chúng có bộ lông ngắn và mượt mà, với màu lông tối ở các vùng cơ thể lớn và màu lông nhạt ở các vùng cơ thể nhỏ. Mèo Siamese thường có đôi mắt xanh lục hoặc xanh lam. Chúng là loài mèo thông minh, tình cảm và thân thiện với con người. Mèo Siamese thường rất gắn bó với chủ nhân của mình và thích tham gia vào mọi hoạt động của gia đình.`,
        origin: "Thái Lan",
        life_span: 15,
        weight: "Dưới 5 Kg",
      },
    ],
  },
];
