import { StyleSheet } from "react-native";
import { FONTS, SIZES, COLORS, ROUNDED } from "../../../constants";

const styles = StyleSheet.create({
    container: {
        height: '100%',
        paddingHorizontal: 20,
        paddingBottom: 2,
    },
    topContent: {
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        paddingTop: 40,
    },
    codeText: {
        fontFamily: FONTS.bold,
        fontSize: 14,
        color: COLORS.slategray,
    },
    idText: {
        fontFamily: FONTS.bold,
        fontSize: 38,
        letterSpacing: 0.1,
        color: COLORS.black,
        paddingTop: 10,
    },
    dateText: {
        fontFamily: FONTS.regular,
        fontSize: 16,
        color: COLORS.slategray,
        paddingTop: 21,
    },
    wrapperIcon: {
        width: 88,
        flexDirection: 'row',
        backgroundColor: COLORS.cancel,
        alignItems: 'center',
        gap: 10,
        paddingVertical: 6,
        paddingHorizontal: 7,
        borderRadius: 8,
        marginTop: 21,
    },
    icon: {
        width: 19,
        height: 19,
    },
    text: {
        fontSize: 14,
        fontFamily: FONTS.bold,
        color: COLORS.white,
    },
    paymentContent: {
        backgroundColor: COLORS.primaryOrder,
        borderColor: COLORS.orange,
        borderRadius: 10,
        display: 'flex',
        flexDirection: 'row',
        gap: 25,
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 18,
        marginTop: 60,
    },
    wrapperPaymentLeft: {
        backgroundColor: COLORS.white,
        borderRadius: 6,
        padding: 5,
    },
    wrapperPaymentRight: {
        borderRadius: 6,
        padding: 5,
    },
    paymentImg: {
        width: 35,
        height: 35,
    },
    paymentTextName: {
        fontSize: 18,
        letterSpacing: 0.1,
        fontFamily: FONTS.bold,
        color: 'black',
    },
    paymentTextDes: {
        fontSize: 14,
        letterSpacing: 0.1,
        fontFamily: FONTS.bold,
        color: COLORS.slategray,
        paddingTop: 8,
    },
    infoContent: {
        backgroundColor: COLORS.primaryOrder,
        borderColor: COLORS.orange,
        borderRadius: 10,
        paddingHorizontal: 20,
        paddingVertical: 20,
        marginTop: 22,
    },
    wrapperInfo: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 18,
    },
    wrapperInfoLeft: {
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#d6d9e1',
        paddingHorizontal: 14,
        paddingVertical: 12,
    },
    wrapperInfoRight: {
        borderRadius: 6,
        padding: 5,
        paddingLeft: 20
    },
    infoImg: {
        width: 35,
        height: 35,
    },
    infoTextName: {
        fontSize: 12,
        letterSpacing: 0.2,
        fontFamily: FONTS.bold,
        color: COLORS.slategray,
    },
    infoTextDes: {
        paddingTop: 4,
        paddingRight: 50,
        fontSize: 14,
        letterSpacing: 0.1,
        fontFamily: FONTS.bold,
        color: 'black',
    },
    noteContent: {
        backgroundColor: COLORS.primaryOrder,
        borderColor: COLORS.orange,
        borderRadius: 10,
        paddingHorizontal: 20,
        paddingVertical: 20,
        marginTop: 12,
    },

    productContent: {
        marginTop: 14,
        borderWidth: 0.3,
        borderRadius: 10,
        borderColor: '#d6d9e1',
    },
    wrapperContent: {
        padding: 20,
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
    },
    wrapperProduct: {
        flex: 0.85,

    },
    textProduct: {
        fontFamily: FONTS.bold,
        letterSpacing: 0.1,
    },
    textPrice: {
        fontFamily: FONTS.bold,
        color: COLORS.slategray,
        paddingTop: 5,
    },
    wrapperQuantity: {
        flex: 0.13,
        height: 42,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: COLORS.primaryOrder,
        borderRadius: 10,
    },
    textQuantity: {
        fontFamily: FONTS.bold,
        color: COLORS.black,
        fontSize: 20,
    },
    deliveryContent: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingTop: 22,
    },
    totalContent: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingTop: 22,
    },
    helpContent: {
        backgroundColor: COLORS.primaryOrder,
        borderRadius: 10,
        display: 'flex',
        flexDirection: 'row',
        gap: 15,
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 18,
        marginTop: 20,
    },
    helpImg: {
        width: 28,
        height: 28,
    },
    wrapperHelpRight: {
        width:'100%',
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    helpTextName: {
        fontSize: 16,
        letterSpacing: 0.1,
        fontFamily: FONTS.bold,
        color: 'black',
    },
    helpTextEmail: {
        fontSize: 14,
        letterSpacing: 0.1,
        fontFamily: FONTS.bold,
        color: 'black',
    },
    helpTextDes: {
        fontSize: 14,
        letterSpacing: 0.1,
        fontFamily: FONTS.regular,
        color: COLORS.black,
    },
});

export default styles;
